// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module offload_Loop_distributor_p0_1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_p0_address0,
        p_p0_ce0,
        p_p0_q0,
        p_p0_to_offload_s0_stream_V_din,
        p_p0_to_offload_s0_stream_V_full_n,
        p_p0_to_offload_s0_stream_V_write
);

parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st6_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv14_0 = 14'b00000000000000;
parameter    ap_const_lv14_64 = 14'b1100100;
parameter    ap_const_lv7_64 = 7'b1100100;
parameter    ap_const_lv7_1 = 7'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [13:0] p_p0_address0;
output   p_p0_ce0;
input  [7:0] p_p0_q0;
output  [7:0] p_p0_to_offload_s0_stream_V_din;
input   p_p0_to_offload_s0_stream_V_full_n;
output   p_p0_to_offload_s0_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_p0_ce0;
reg p_p0_to_offload_s0_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_22;
reg    p_p0_to_offload_s0_stream_V_blk_n;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg   [0:0] exitcond5_i_i_reg_162;
reg   [0:0] ap_reg_ppstg_exitcond5_i_i_reg_162_pp0_iter1;
reg   [6:0] p_distributor_p0_0_0_i_i_reg_93;
wire   [13:0] next_mul_fu_104_p2;
reg   [13:0] next_mul_reg_148;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_60;
wire   [0:0] exitcond6_i_i_fu_110_p2;
wire   [6:0] p_distributor_p0_1_fu_116_p2;
reg   [6:0] p_distributor_p0_1_reg_157;
wire   [0:0] exitcond5_i_i_fu_126_p2;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_72;
reg    ap_sig_76;
wire   [6:0] p_distributor_p0_0_fu_132_p2;
wire   [13:0] p_268_fu_138_p2;
reg   [13:0] p_268_reg_171;
reg   [6:0] p_distributor_p0_1_0_i_i_reg_70;
reg    ap_sig_104;
reg    ap_sig_cseq_ST_st6_fsm_3;
reg    ap_sig_112;
reg   [13:0] phi_mul_reg_81;
wire   [63:0] tmp_i_fu_144_p1;
wire   [13:0] p_distributor_p0_0_0_i_i_cast_fu_122_p1;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'b1;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond6_i_i_fu_110_p2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & ~(1'b0 == exitcond5_i_i_fu_126_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond6_i_i_fu_110_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & (1'b0 == exitcond5_i_i_fu_126_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond6_i_i_fu_110_p2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & ~(1'b0 == exitcond5_i_i_fu_126_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond6_i_i_fu_110_p2))) begin
            ap_reg_ppiten_pp0_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & (1'b0 == exitcond5_i_i_fu_126_p2))) begin
        p_distributor_p0_0_0_i_i_reg_93 <= p_distributor_p0_0_fu_132_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond6_i_i_fu_110_p2))) begin
        p_distributor_p0_0_0_i_i_reg_93 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st6_fsm_3)) begin
        p_distributor_p0_1_0_i_i_reg_70 <= p_distributor_p0_1_reg_157;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_104)) begin
        p_distributor_p0_1_0_i_i_reg_70 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st6_fsm_3)) begin
        phi_mul_reg_81 <= next_mul_reg_148;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_104)) begin
        phi_mul_reg_81 <= ap_const_lv14_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76))) begin
        ap_reg_ppstg_exitcond5_i_i_reg_162_pp0_iter1 <= exitcond5_i_i_reg_162;
        exitcond5_i_i_reg_162 <= exitcond5_i_i_fu_126_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        next_mul_reg_148 <= next_mul_fu_104_p2;
        p_distributor_p0_1_reg_157 <= p_distributor_p0_1_fu_116_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & (1'b0 == exitcond5_i_i_fu_126_p2))) begin
        p_268_reg_171 <= p_268_fu_138_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond6_i_i_fu_110_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond6_i_i_fu_110_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_72) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_60) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_112) begin
        ap_sig_cseq_ST_st6_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76))) begin
        p_p0_ce0 = 1'b1;
    end else begin
        p_p0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond5_i_i_reg_162_pp0_iter1 == 1'b0))) begin
        p_p0_to_offload_s0_stream_V_blk_n = p_p0_to_offload_s0_stream_V_full_n;
    end else begin
        p_p0_to_offload_s0_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond5_i_i_reg_162_pp0_iter1 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76))) begin
        p_p0_to_offload_s0_stream_V_write = 1'b1;
    end else begin
        p_p0_to_offload_s0_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~ap_sig_104) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == exitcond6_i_i_fu_110_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & ~(1'b0 == exitcond5_i_i_fu_126_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_76) & ~(1'b0 == exitcond5_i_i_fu_126_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st6_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st6_fsm_3 : begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_104 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_sig_112 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_22 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_60 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_72 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_76 = ((ap_reg_ppstg_exitcond5_i_i_reg_162_pp0_iter1 == 1'b0) & (p_p0_to_offload_s0_stream_V_full_n == 1'b0));
end

assign exitcond5_i_i_fu_126_p2 = ((p_distributor_p0_0_0_i_i_reg_93 == ap_const_lv7_64) ? 1'b1 : 1'b0);

assign exitcond6_i_i_fu_110_p2 = ((p_distributor_p0_1_0_i_i_reg_70 == ap_const_lv7_64) ? 1'b1 : 1'b0);

assign next_mul_fu_104_p2 = (phi_mul_reg_81 + ap_const_lv14_64);

assign p_268_fu_138_p2 = (phi_mul_reg_81 + p_distributor_p0_0_0_i_i_cast_fu_122_p1);

assign p_distributor_p0_0_0_i_i_cast_fu_122_p1 = p_distributor_p0_0_0_i_i_reg_93;

assign p_distributor_p0_0_fu_132_p2 = (p_distributor_p0_0_0_i_i_reg_93 + ap_const_lv7_1);

assign p_distributor_p0_1_fu_116_p2 = (p_distributor_p0_1_0_i_i_reg_70 + ap_const_lv7_1);

assign p_p0_address0 = tmp_i_fu_144_p1;

assign p_p0_to_offload_s0_stream_V_din = p_p0_q0;

assign tmp_i_fu_144_p1 = p_268_reg_171;

endmodule //offload_Loop_distributor_p0_1_proc
