#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("p_p0_address0", 14, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("p_p0_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("p_p0_d0", 8, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("p_p0_q0", 8, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("p_p0_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("p_p0_address1", 14, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("p_p0_ce1", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("p_p0_d1", 8, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("p_p0_q1", 8, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("p_p0_we1", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("p_offload_address0", 14, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("p_offload_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("p_offload_d0", 8, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("p_offload_q0", 8, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("p_offload_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("p_offload_address1", 14, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("p_offload_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("p_offload_d1", 8, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("p_offload_q1", 8, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("p_offload_we1", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "offload";
